### ISSUE TITLE
Property Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#1]
Property (building):
  name:  string
  *address: [Address]
  yearBuilt: integer (1500 - 2050)
  numberOfStories: integer (positive)
  lotSize: float (positive)
  apn: string (non-empty)
  *price: float (positive)
  totalSquareFeet: float
 
Relations:
has many: property units
has one: user

API endpoints:
List
Read
Create
Update
Delete

**Comment by Sjefkesuit** [comment]
@m-ke APN is just a random string of numbers. Like an ID in a database. So I think that would make it an integer field.

**Comment by m-ke** [comment]
thanks @Sjefkesuit! will store it as a string then, since it's not used for calculations anywhere

**Comment by Sjefkesuit** [comment]
For now it is ok to only have 1 user.

However we should set it up where a property can have multiple users as often times people work in teams and there will be multiple agents/users related to the same property in the package.

Not necessary for MVP but if it is the same amount of work to set that up differently it is good to know.

**Comment by Sjefkesuit** [comment]
We should add the following fields to this (all not required):

water: string 
electric: string 
gas: string 
foundation: string 
framing: string 
exterior: string 
parkingSurface: string 
roof: string

**Comment by m-ke** [comment]
1) we should then talk about how we want to structure the users / whether in companies or within smaller units and whether these user groups would be permanent or they'd be different for each package

2) what are those fields for, could you please give some context? what do they mean?

**Comment by Sjefkesuit** [comment]
1. For time being lets keep it at 1 user in that case. Not worth over complicating things for now. It would require an agent bio for each user.
2. See below for example.
![property details](https://user-images.githubusercontent.com/33290928/49608647-7733dc00-f999-11e8-8c09-d559ddaae1b4.JPG)

**Comment by m-ke** [comment]
@Sjefkesuit Will this be like with the operating statement, that people will be able to add/ remove items, rename fields etc? if so, and if the total number of rows is going to change again, I'd not change what we have right now (it's not in the template now anyways) and I'd add it as v2 feature request - we can discuss the details & add it to the backlog.

**Comment by m-ke** [comment]
assigning to myself to check & close

**Comment by Sjefkesuit** [comment]
@m-ke yes, ok to consider it as feature and put it in V2. But to answer the question, no won't be like the operating statement, no flexibility for the user. They would be included in each package as they are included in each package, so in that sense they are very much like the other data points in the property mode. It would be as simple as adding a few lines to that sheet, no need for additional page or anything. However for time being lets put on list for V2 and if somehow we run out of things before end of Jan we can pick it up.

**Comment by m-ke** [comment]
required fields are not set as required in DB

```
dbe33qag7g6hp8=> \d properties
                                 Table "public.properties"
      Column       |            Type             | Collation | Nullable |      Default      
-------------------+-----------------------------+-----------+----------+-------------------
 id                | uuid                        |           | not null | gen_random_uuid()
 name              | character varying           |           |          | 
 year_built        | integer                     |           |          | 
 number_of_stories | integer                     |           |          | 
 lot_size          | double precision            |           |          | 
 apn               | character varying           |           |          | 
 price             | double precision            |           |          | 
 total_square_feet | double precision            |           |          | 
 created_at        | timestamp without time zone |           | not null | 
 updated_at        | timestamp without time zone |           | not null | 
 package_id        | uuid                        |           |          | 
 user_id           | uuid                        |           |          | 
 address_id        | uuid                        |           |          | 
Indexes:
    "properties_pkey" PRIMARY KEY, btree (id)

```

**Comment by marionschleifer** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/5722022/50526336-ae516500-0ae1-11e9-9561-005159597d51.png)
