### ISSUE TITLE
Operating statement

### ISSUE THREAD

**Issue by marionschleifer** [cre-project/cre-backend#14]

**Comment by Sjefkesuit** [comment]
@m-ke and @marionschleifer we will wait to have a look after you have a pass at the content here. As mentioned earlier it is probably worth looking to see if there are open source libraries we can just use for creation of this part. Other names are:

Operating Statement
Profit and Loss statement
Income Statement

They are all basically the same thing.

Important in our case are:
On the INCOME side:
Gross potential rent (calculated as total of rent from Property Units times 12 months)
Adjustment for Vacancy (Negative amount) set as % of gross potential rent
Option for multiple items of Other Income

On the Expense side:
Real Estate Tax (Either percentage or be able to provide amount directly)
Management Fee (Either percentage or be able to provide amount directly)
Other expense items they should be able to add line items and name them.

As mentioned in Property Unit. If no information is provided on Pro Forma amounts per unit there should not be a column for Pro Forma.

**Comment by Sjefkesuit** [comment]
User should have the ability to rename the column headers.

For instance instead of Pro Forma be able to change it to Year 2, or Year 1 (should be custom)

Also to specify, User should be able to name the line items for Income and Expense items.

**Comment by m-ke** [comment]
re: libraries 

Here's a list I found, we should go over it next week to see if any fits (also so that it's not a complete overkill)
    https://github.com/ledermann/keepr 
    https://github.com/mbulat/plutus
    https://github.com/betterplace/acts_as_account
    https://github.com/steveluscher/bookkeeper
    https://github.com/mstrauss/double-entry-accounting
    https://github.com/logicleague/double_booked
    https://github.com/telent/pacioli
    https://github.com/astrails/deb
    https://github.com/bigfleet/accountable

**Comment by Sjefkesuit** [comment]
@m-ke , yes fully agree that we should be careful not to go overboard. The entire point of using library would be to save dev time on making some features work such as the adding and renaming line items. We definitely don't need double entry accounting. I will look thru and see what I can find so we can discuss and decide this week.

**Comment by Sjefkesuit** [comment]
The Accounting library is no longer applicable. Will use Buefy
