### ISSUE TITLE
Operating statement fields

### ISSUE THREAD

**Issue by marionschleifer** [cre-project/cre-backend#15]
* name: string
* currentValue: float
potentialValue: float
* isIncome: bool, default false

belongs_to: operating statement

**Comment by m-ke** [comment]
please make the name & is_income required in DB, thanks!

**Comment by marionschleifer** [comment]
Sure, done:
![image](https://user-images.githubusercontent.com/5722022/50526472-99290600-0ae2-11e9-9dfd-373cfed81694.png)
