### ISSUE TITLE
Property Unit Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#2]
*Bedrooms: Enum (Studio, 1, 2, 3, 4)
*Bathrooms:  One of 1, 1.5, 2, 2.5, 3
*Current Rent: Float (+)
Potential Rent: Float (+)

API endpoints:
List
Create 
Delete

**Comment by Sjefkesuit** [comment]
These are good and correct.

To keep in mind, if Potential Rent is left blank there should not be a column for Pro Forma on the Operating Statement. It should only show the current column in those cases.

**Comment by m-ke** [comment]
does that mean the field wouldn't be editable?

**Comment by Sjefkesuit** [comment]
@m-ke I don't think I am understanding your question.

The Potential rent field should behave the same as the Current Rent field except that it should not be required to be completed. So if left blank or at 0 it should not result in a column on the operating statement.

**Comment by m-ke** [comment]
@marionschleifer  assigning to myself to check & close

**Comment by Sjefkesuit** [comment]
@m-ke yes that understanding is indeed correct and we can indeed treat it as a feature request.

**Comment by m-ke** [comment]
Required fields are not set as not nullable in DB:
```
dbe33qag7g6hp8=> \d property_units
                              Table "public.property_units"
     Column     |            Type             | Collation | Nullable |      Default      
----------------+-----------------------------+-----------+----------+-------------------
 id             | uuid                        |           | not null | gen_random_uuid()
 bedrooms       | integer                     |           |          | 
 bathrooms      | double precision            |           |          | 
 current_rent   | double precision            |           |          | 
 potential_rent | double precision            |           |          | 
 created_at     | timestamp without time zone |           | not null | 
 updated_at     | timestamp without time zone |           | not null | 
 property_id    | uuid                        |           |          | 
Indexes:
    "property_units_pkey" PRIMARY KEY, btree (id)
```

**Comment by marionschleifer** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/5722022/50526164-88779080-0ae0-11e9-91e6-9c489948f45b.png)
