### ISSUE TITLE
Assess accounting libraries

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#20]
From #14 

@Sjefkesuit I'll need your help with this

Assess following libraries:
https://github.com/ledermann/keepr
https://github.com/mbulat/plutus
https://github.com/betterplace/acts_as_account
https://github.com/steveluscher/bookkeeper
https://github.com/mstrauss/double-entry-accounting
https://github.com/logicleague/double_booked
https://github.com/telent/pacioli
https://github.com/astrails/deb
https://github.com/bigfleet/accountable

**Comment by Sjefkesuit** [comment]
@m-ke 

Thanks for looking up some options. I went thru some and think the very obvious conclusion is that looking for accounting solution is overkill for us from the start.

The only thing we really need is a library that supports the basic functionality we are looking for, being able to add, edit, delete and rename rows in a table format and perform some simple calculations on top of that.

Did a quick search and I think there are some options out there, like for instance:
https://www.ag-grid.com/vue-getting-started/
https://github.com/bogdan/datagrid
https://github.com/hunterae/table-for
http://tabulator.info/

Overview for Ruby:
https://www.ruby-toolbox.com/categories/Table_Builders

Lets discuss. It seems strange if we would have to build this from scratch ourselves but also hard for me to judge how much work is involved in making any of these solutions work.

**Comment by Sjefkesuit** [comment]
As per discussion with @m-ke , no longer needed. We will work with Buefy where needed.
