### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by marionschleifer** [cre-project/cre-backend#25]
* add column to user db table: **reset_token**

1) **Request password reset** email

- API:

  - endpoint ```/api/auth/request-reset```

- Request:

  -  POST ```{email: 'email'}```

* backend checks whether the email is in the DB
* if it is, sends an email with a link to dashboard
```<dashboard-url>/reset/<token>```
token: generate uuidV4, store in DB as reset_token
* send 200OK as a response (regardless of whether the user exists)

2) **Reset password** 

* API:
  * POST ```/api/auth/reset/<token>```
  * body: ```{password: 'pwd'}```
* check if token is valid, if not return a 400 error
* if token is valid, save bcrypted password in db & return 200ok

**Comment by marionschleifer** [comment]
The endpoints are:
/api/passwords/request_reset
/api/passwords/reset

**Comment by m-ke** [comment]
Made an issue for this in the current sprint. the request_resets returns 404 when the email is not found, that has to be fixed #48
