### ISSUE TITLE
Address Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#3]
*Street Name: string
street number: string
*city: string
state: string
*zip: integer

belongs to: property, sold properties, rented units, user

Address saved in a separate table but no direct API endpoints

**Comment by marionschleifer** [comment]
Note: we discussed that the address doesn't know to which model it belongs, so no need for associations inside the address.

**Comment by Sjefkesuit** [comment]
@marionschleifer 

All of the fields should be required (State and street number as well):
Street number should be together probably in the same field as street name, they always belong together. 

The order is correct.

**Comment by m-ke** [comment]
@marionschleifer we should check how the google maps API returns the address and update the fields accordingly (we'll use lookup in the frontend to autofill)

**Comment by Sjefkesuit** [comment]
@m-ke , yes if we can implement Google maps API for autofill as well as part of this effort that would be fantastic indeed. As our product is all about speed for the user that should hopefully be an "easy" win.

**Comment by marionschleifer** [comment]
@m-ke @Sjefkesuit The Google maps API should return something like this:
```
"formatted_address" : "1600 Amphitheatre Parkway, Mountain View, CA 94043, USA"
```
So, as Sjef said, the street name and the street number should be in the same field. I will change that. Also, I think country is not important at this point, we can always include it later.
