### ISSUE TITLE
Write text for password reset email

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#35]
The one thing it should include is that the reset link is only valid for 4 hours (can be changed if we decide to change it)

**Comment by Sjefkesuit** [comment]
Thanks @m-ke, I suggest we keep it very straight forward. Ideally with some decent lay out but at the beginning just in line text is fine. 

E-mail Subject: Password Reset Offering CRE
E-mail address from: info@offeringcre.com (If relevant)

Hello,

We have received a request from you or someone else to reset the password of your Offering CRE account. Please click on the link below to reset your password.

<LINK (If possible the text that shows states: Reset Password)>

If you do not wish to change your password you can simply ignore this email.

Best Regards,
The Offering CRE Team

**Comment by m-ke** [comment]
@marionschleifer  here's the text

**Comment by marionschleifer** [comment]
@m-ke @Sjefkesuit Thank you, I will integrate it :)

**Comment by m-ke** [comment]
Pls also include the 4 hours :)

**Comment by marionschleifer** [comment]
It's already included 👍

**Comment by Sjefkesuit** [comment]
Sorry @m-ke  I completely forgot. Thanks for including it nevertheless @marionschleifer
