### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#4]
- [x] Setup Rails project (testing environment) with a testing suite. 
- [x] Name of the Heroku project: cre-backend-testing
- [x] Connect it to a Heroku Postgres instance
- [x] Pick a logging addon on Heroku (such as papertrail)
- [x] Setup Heroku deployment
- [x] Check firebase auth integration (whether it's possible / easy)

**Comment by Sjefkesuit** [comment]
@m-ke it probably doesn't matter anymore as we are changing entire set up but I see Firebase mentioned in this issue so just wanted to make sure in any case that we use a different one from before as the API key was posted public before. Feel free to ignore this comment if not relevant.
