### ISSUE TITLE
Endpoint for subscription changed/ expired

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#43]
Webhook like for user/create

POST to user/subscription_changed

Update the expiration (`expiry_date` in request) & subscription (`product_id` in request)

https://www.pabbly.com/subscriptions/webhooks/

**Comment by marionschleifer** [comment]
@m-ke Could you send a request from pabbly to test this? 😄 

This is the endpoint: `/api/user/subscription_changed`

**Comment by m-ke** [comment]
:100: :1st_place_medal:
