### ISSUE TITLE
Sold Properties Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#5]
yearBuilt: integer (+)l
 * salesPrice: float (+)
 * numUnits: integer (+)
  squareFeet: Float (+)
  capRate: float (+)
  grm: float (+)
  closeOfEscrow: date
  imageUrl: string

* has one: address [Address] 
has one: user

API Endpoints: 
List
Create
Update
Delete

**Comment by Sjefkesuit** [comment]
Some items in here are only for Rental Units, not applicable to Sold Properties:

rent: integer (+)
bedrooms: like in Property Unit model
bathrooms: like in Property Unit model

Missing field:
squareFeet: Float (+)

Option not to add any sold property but when done the following fields should be required:
address
salesPrice
numUnits

Other things to keep in mind:
pricePerUnit
pricePerSf
Are calculations. The salesPrice divided by the numUnits or squareFeet (respectively).

This goes for all forms/models, when none required fields are left blank they should not populate in the preview/package.

**Comment by m-ke** [comment]
@marionschleifer  I updated the description, you can implement it according to that
