### ISSUE TITLE
API Endpoints

### ISSUE THREAD

**Issue by marionschleifer** [cre-project/cre-backend#6]
Property 
- [x] API endpoints
- [x] Model 
- [x] Tests

Rent units
- [x] API endpoints
- [x] Model 
- [x] Tests

Sold properties
- [x] API endpoints
- [x] Model 
- [x] Tests

Property units
- [x] API endpoints
- [x] Model 
- [x] Tests

Operating statement
- [ ] API endpoints
- [ ] Model 
- [ ] Tests

OS fields
- [x] API endpoints
- [x] Model 
- [x] Tests

User / agent
- [x] API endpoints
- [x] Model 
- [x] Tests

Address
- [x] API endpoints
- [x] Model 
- [x] Tests

Package
- [x] API endpoints
- [x] Model 
- [x] Tests

Company
- [x] API endpoints
- [x] Model 
- [x] Tests

**Comment by m-ke** [comment]
When you set up the database could you please set the primary key as UUID? auto-generated, just not the autoincrementing int but UUID

**Comment by marionschleifer** [comment]
@m-ke Yes, it's done! 👍

**Comment by m-ke** [comment]
closing this as there's a follow-up issue for OS (#62 )
