### ISSUE TITLE
User Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#7]
firstName: String 
  lastName: string
  *email: string, required, unique (case-insensitive)
  licenseNumber: string
  phoneNumber: US phone number, string
  fax: US phone number, string
  companyName: string
  websiteUrl: string
  title: string 
 subscriptionExpiration: date

API endpoints:
Read
Create
Update
Delete

**Comment by m-ke** [comment]
Let's do it the other way around with the closings and packages: 

- they will belong to users (ie package has one user)

**Comment by m-ke** [comment]
For the delete API method, please only return a 501 "not implemented" error (we'll implement it later)

**Comment by m-ke** [comment]
that's interesting, we were talking specifically about having the description - has something changed? the agents seem to always have a short bio in those materials

**Comment by Sjefkesuit** [comment]
Yes, after discussion with Sonny the decision is to not include an Agent Bio section in the package at first, as that would require to also build out the part that includes all the recently sold properties from that agent etc.

As per feedback of actual potential user they mentioned they can have that section separate as it is the same each time and does not have to be part of the property package. It should be at some point but to keep our efforts focused better to leave out for time being. 

If in January we have time left we can add it in.

**Comment by marionschleifer** [comment]
I had to change the phone number to string, because as an Integer, it was too large to handle for Ruby :D

**Comment by m-ke** [comment]
that's actually a good thing :+1:  phone numbers should be saved as string. @marionschleifer can you pls add the fax number? same validation as for the phone number

**Comment by marionschleifer** [comment]
@m-ke Yes, done 👍

**Comment by marionschleifer** [comment]
@m-ke Yes, I was going to combine that with the CREATE User API and make the company a nested model of the user. Because the company never exists without a user, right? If it can, I'll leave them separate and add a foreign key.
