### ISSUE TITLE
Package Model

### ISSUE THREAD

**Issue by marionschleifer** [cre-project/cre-backend#8]
template / templateID  (string) -> will be the identifier of pdf template for the pdf export service

has_one: property
has_many: rentalUnits
has_many: soldProperties
pictures (? research!)

API endpoints
List
Read
Create
Edit (needs more implementation details later)
Delete

**Comment by marionschleifer** [comment]
@Sjefkesuit @m-ke Does this mean that `Template` / `Design` should be a separate model?

**Comment by Sjefkesuit** [comment]
@marionschleifer according to quick discussion with @m-ke on this subject yesterday, no, no need for separate model for this. Correct me if I am wrong here @m-ke

**Comment by m-ke** [comment]
I updated the description. it's just an identifier of a template we'll use for the pdf export. right now we only have one but later on we'll have multiple (or color variations)

it can default either to null or 'default' string

**Comment by marionschleifer** [comment]
Ok thank you 👍

**Comment by marionschleifer** [comment]
Note: I left the pictures out for now, as this needs more discussion / research. It will be a ticket in the next sprint and I can add them later to the model.

**Comment by Sjefkesuit** [comment]
On these two:

has_many: rentalUnits
has_many: soldProperties

There will also be proposals that have None for these as well.

**Comment by m-ke** [comment]
yes. has_many is a bit misleading since it means it could be from 0 to many

**Comment by m-ke** [comment]
assiging to myself to check & close

**Comment by Sjefkesuit** [comment]
Ok perfect, wasn't sure about that so thanks for clarifying.

**Comment by m-ke** [comment]
there are some inconsistencies - rented unit id and sold property id should not be there since we have tables that link packages and these other two tables
```

dbe33qag7g6hp8=> \d packages
                                       Table "public.packages"
      Column      |            Type             | Collation | Nullable |           Default            
------------------+-----------------------------+-----------+----------+------------------------------
 id               | uuid                        |           | not null | gen_random_uuid()
 template         | character varying           |           |          | 'default'::character varying
 created_at       | timestamp without time zone |           | not null | 
 updated_at       | timestamp without time zone |           | not null | 
 property_id      | uuid                        |           |          | 
 rented_unit_id   | uuid                        |           |          | 
 sold_property_id | uuid                        |           |          | 
 user_id          | uuid                      
```

**Comment by marionschleifer** [comment]
@m-ke Thank you for the reminder, I removed it:

![image](https://user-images.githubusercontent.com/5722022/50527706-5539ff00-0aea-11e9-8496-31fc2e33e58a.png)

Should I add the tables that link packages and the two other tables to packages? It doesn't seem very clean to do it, but how else should we load them when /package/:id should return all the other objects with eager loading?
