### ISSUE TITLE
Rented Unit Model

### ISSUE THREAD

**Issue by m-ke** [cre-project/cre-backend#9]
yearBuilt: integer (+)
*bedrooms: like in Property Unit model
bathrooms: like in Property Unit model
*currentRent: float (+)
imageUrl: string

has one: address [Address]
has one: user

API Endpoints:
List
Create
Update
Delete

**Comment by Sjefkesuit** [comment]
Looks like we confused rental units with the sold property fields. The Rented Unit should NOT include the following fields:

salesPrice: float (+)
numUnits: integer (+)
pricePerUnit: float(+)
pricePerSf: float (+)
capRate: float (+)
grm: float (+)
closeOfEscrow: date

Should be option not to add any, but when a unit is added the following should apply:
Address should be required field
Bedroom should be required field (bathroom NOT)
Current rent should be required field

@m-ke can you clarify what you mean with has 1 user? (they show up only in the account of that user?)

**Comment by m-ke** [comment]
@Sjefkesuit yes, exactly

**Comment by m-ke** [comment]
@marionschleifer I updated the description, please implement according to that

**Comment by m-ke** [comment]
Required fields are not set as required in DB

**Comment by marionschleifer** [comment]
Done:
![image](https://user-images.githubusercontent.com/5722022/50526554-148ab780-0ae3-11e9-9af3-7136216c5a2e.png)
